### ISSUE TITLE
Provide NuGet package on nuget.org

### ISSUE THREAD

**Issue by frankneumann** [fugro/g2o#1]
If possible, could you please supply a NuGet package on nuget.org for your library?

Thanks for your nice work,

Frank

**Comment by mvdfugro** [comment]
This took a little while, but we are now published on Nuget (includes assemblies for both .NET Core and .NET Framework): https://www.nuget.org/packages/Fugro.G2O/2.0.1

**Comment by valeriob** [comment]
Thanks !
Does the nuget package include the native dependency ?
EDIT : nevermind, i just saw it's a c++/cli project :D

**Comment by mvdfugro** [comment]
Hi @valeriob! Indeed, it's a C++/CLI project, which has the G2O dependencies (Eigen, csparse) compiled-in/statically linked. Note that, even though the C++/CLI wrapper is MIT licensed, the whole is essentially LGPL-2.1 licensed.
