### ISSUE TITLE
How to add edge?

### ISSUE THREAD

**Issue by applefl** [fugro/g2o#2]
The example only has an AddObservation function, but how to add edges to a graph?

**Comment by HWouters** [comment]
AddObservation adds an edge

**Comment by applefl** [comment]
Thank you for reply. Could you please give an example, such as fitting a straight line?

**Comment by HWouters** [comment]
You can find more examples in the unit tests.

For a straight line you should do something like this:
- define state class with a state of 2 parameters (double[]). Create one state instance in this example, because you have one line
- define observation class with a(2D point?) as measurement. Implement the error function, OnComputeError. (closest distance between estimated line and the point?)
- instantiate an observation for each 2D point, link it to the state and add them to the graph.

**Comment by applefl** [comment]
Thanks. I followed your steps. Here is my code, but the output was a=-114.395413035757, b=-48.87622303416 which are actually should be a=10, b=5. Is there any error in my code?
```
        class State : State<double[]>
        {
            public State(double[] initialValue)
                : base(initialValue, 2)
            { }

            protected override double[] OnUpdate(double[] delta)
            {
                for (int i = 0; i < delta.Length; i++)
                {
                    Estimate[i] += delta[i];
                }
                return Estimate;
            }
        }

        class Measurement : Observation
        {
            private readonly double _x;
            private readonly double _y;
            private readonly State m_State;

            public Measurement(double x, double y, State state, double sd = 1.0)
                : base(new[] { sd }, state)
            {
                m_State = state;
                _x = x;
                _y = y;
            }

            protected override double[] OnComputeError()
            {
                var error = _y - (_x * m_State.Estimate[0] + m_State.Estimate[1]);

                return new[] { error };
            }
        }

        double[] init = new double[2];
        init[0] = 0;
        init[1] = 0;
        var state = new State(init);

        var graph = new Graph();
        double a = 10, b = 5;
        for (int i = 0; i < 10; i++)
        {
                double x = i;
                double y = a * x + b;

                var measurement = new Measurement(x, y, state);
                graph.AddObservation(measurement);
        }
        graph.Optimize();
        Console.WriteLine(state.Estimate[0]);
        Console.WriteLine(state.Estimate[1]);
```

**Comment by HWouters** [comment]
The code looks correct to me. I would try another error function for better convergence. Perhaps calculate the closest distance between point and line. 
For debugging you can wire up an event handler to the graph and check how it convergences and what is the error residual

**Comment by applefl** [comment]
OK. I will try it. Thanks a lot!
